### ISSUE TITLE
Create builds for Nodejs and the Browser

### ISSUE THREAD

**Issue by buccfer** [workast/workast-sdk-js#15]
We should:

- lib/
  - Code transpiled to ES5
  - Uses UMD to support both Nodejs and front-end frameworks
  - No minification or source maps needed. Code should be as legible as possible.
  - Dependencies should NOT be added to the bundle.

- dist/
  - Code transpiled to ES5
  - No need for UMD since this is going to be used in Browsers through the script tag
  - Should be minified and have production source maps. (.min.js and .js versions)
  - Dependencies should be added to the bundle to work correctly
   
Notes:
- Both folders should be added to .gitignore
- Both folders should be in "files" in package.json
- The "main" in package.json should be "lib/workast.js"
- I think we should target at least the same environments as the superagent library, since we are relying on it to make http requests. See https://github.com/visionmedia/superagent/blob/master/.browserslistrc
Our recomendation is:

```
"browserslist": [
   "> 1%",
  "last 2 versions",
  "not dead",
  "maintained node versions"
]
```

**Comment by MatiasFito** [comment]
Resolved by #19
